# Generated by Django 2.0.3 on 2018-04-05 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='-', max_length=20, null=True)),
                ('surname', models.CharField(blank=True, default='-', max_length=20, null=True)),
                ('phone', models.CharField(blank=True, default='-', max_length=15, null=True)),
                ('description', models.TextField(blank=True, default='-', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IndDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=True, max_length=60, null=True, verbose_name='Название курса')),
                ('price', models.IntegerField(blank=True, default=0, null=True, verbose_name='Цена за акч')),
                ('des_hours', models.CharField(default='-', max_length=40, null=True, verbose_name='Желательное кол ак часов')),
                ('coach', models.ManyToManyField(blank=True, default='-', null=True, related_name='coachs', to='ind_school.Coach', verbose_name='Преподаватель')),
            ],
        ),
    ]
