# Generated by Django 2.0.3 on 2018-04-06 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design_school', '0002_auto_20180406_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='name',
            field=models.CharField(blank=True, default='-', max_length=20, null=True),
        ),
    ]
