# Generated by Django 2.0.3 on 2018-04-27 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('design_school', '0003_auto_20180406_1411'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesignSetGetGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(blank=True, default=' ', max_length=150, verbose_name='ФИО')),
                ('date_add', models.CharField(blank=True, default=' ', max_length=100, verbose_name='Дата записи')),
                ('phone', models.CharField(blank=True, default=' ', max_length=20, verbose_name='Телефон')),
                ('email', models.CharField(blank=True, default=' ', max_length=50, verbose_name='Емейл')),
                ('discount', models.CharField(blank=True, default=' ', max_length=40, verbose_name='Скидка')),
                ('note', models.CharField(blank=True, default=' ', max_length=100, verbose_name='Примечание')),
            ],
        ),
        migrations.CreateModel(
            name='Manth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manth', models.CharField(blank=True, default=' ', max_length=20, verbose_name='Месяц')),
            ],
        ),
        migrations.AddField(
            model_name='designdetail',
            name='set_or_work',
            field=models.CharField(choices=[('s', 'собирается'), ('w', 'работает')], default='s', max_length=1),
        ),
        migrations.AddField(
            model_name='designsetgetgroups',
            name='info_course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='design_detail', to='design_school.DesignDetail', verbose_name='инфо курса'),
        ),
    ]
