# Generated by Django 2.0.3 on 2018-04-27 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design_school', '0004_auto_20180427_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designdetail',
            name='set_or_work',
            field=models.CharField(choices=[('s', 'собирается'), ('w', 'работает')], max_length=1),
        ),
    ]
