# Generated by Django 2.0.3 on 2018-05-02 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design_school', '0005_auto_20180427_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designdetail',
            name='set_or_work',
            field=models.CharField(choices=[('s', 'собирается'), ('w', 'работает')], max_length=1, verbose_name='позиция'),
        ),
    ]
