# Generated by Django 2.0.3 on 2018-05-04 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('design_school', '0007_auto_20180504_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designsetgetgroups',
            name='info_course',
            field=models.ForeignKey(default=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='design_detail', to='design_school.DesignDetail', verbose_name='инфо курса'),
        ),
    ]
