# Generated by Django 2.0.3 on 2018-04-05 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='-', max_length=20, null=True)),
                ('surname', models.CharField(blank=True, default='-', max_length=20, null=True)),
                ('phone', models.CharField(blank=True, default='-', max_length=15, null=True)),
                ('description', models.TextField(blank=True, default='-', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LangDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, default='-', null=True, verbose_name='Описание')),
                ('price', models.IntegerField(blank=True, default=0, null=True, verbose_name='Цена за курс')),
                ('discount', models.IntegerField(blank=True, default=0, null=True, verbose_name='Скидка')),
                ('time_to_class', models.CharField(blank=True, default='-', max_length=40, null=True, verbose_name='Режим занятий')),
                ('date_to_start', models.CharField(blank=True, default='-', max_length=40, null=True, verbose_name='Дата старта занятий')),
                ('count_students_in_group', models.CharField(blank=True, default=0, max_length=40, null=True, verbose_name='Количество человек в группе')),
                ('count_students', models.IntegerField(blank=True, default=0, null=True, verbose_name='Количество записанных')),
                ('coach', models.ManyToManyField(blank=True, default='-', null=True, related_name='coachs', to='lang_school.Coach', verbose_name='Преподаватель')),
            ],
        ),
        migrations.CreateModel(
            name='LangTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_cours', models.CharField(default=' ', max_length=255, verbose_name='Название курса')),
                ('description', models.TextField(blank=True, default=' ', null=True, verbose_name='Описание курса')),
            ],
        ),
        migrations.AddField(
            model_name='langdetail',
            name='title',
            field=models.ForeignKey(default=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='design_title', to='lang_school.LangTitle', verbose_name='Имя курса'),
        ),
    ]
